### PR TITLE
Add ability to override Wss4J default values for InclusivePrefixes

### PR DESCRIPTION
**Pull request by free-ice**
This adds the ability to control wss4j's InclusivePrefixes settings.

This sets the defaults to match wss4j defaults.

https://github.com/spring-projects/spring-ws/pull/75 should be closed since it would have changed the default behavour of spring-ws.

Tests verify changes and I feel some of the test are overkill but I wanted to ensure that there was no reason not to merge this PR.

I have tested these changes in the 2.4.7 branch of spring-ws, and will be upgrading to this version once the change is merged.

Thanks!

### CODE REVIEW

**Comment by free-ice** [comment]
@gregturn Any feedback would be welcome.

**Comment by free-ice** [comment]
I'll be moving to a new client between Feb 2022 and April 2022. If there are any required changes now is the time to make comments since after that time I will not have a way to manually test any requested changes in a meaningful way.

**Comment by free2create** [comment]
@gregturn @rmagrin would you be able to assign a reviewer to this? I opened this about a year ago and would love to do what I can to see this merged.

Thanks

**Comment by Gulo67** [comment]
I commented on this solution 4 years ago and asked for a release. I don't understand why this can't finally be solved. Compatibility has broken down between wss4j 1.5.x and 2.0.x anyway.

**Comment by free2create** [comment]
Greg seems to be the only/main contributor to spring-ws and it seems he is just trying to keep the lights on. Doing OSS can really suck if the projects you work on are on your own time AND you don't use the project yourself. That's not to say its not frustrating, since I don't know if I am not doing something I should be to make the enhancement acceptable.

The Wss4J team also seems to be down to one developer , but Colon(Wss4j) provides good feedback after gentle prodding, so at least the core framework is on better footing.

**Comment by free2create** [comment]
@gregturn 
I see you made a comment on a similar PR #1239 earlier today, can you review this PR please?

**Comment by Gulo67** [comment]
Yes #1239 is similar, so please give this PR a chance and merge it into release 👍

**Comment by free2create** [comment]
@gregturn I no longer have access to the `free-ice` account since two-factor is enabled. Can you close this PR and I'll create another PR to resolve the merge conflicts. Thanks!

**Comment by free2create** [comment]
Please close, This PR is super ceded by PR #1300

**Pull request closed without merging**
