### PR TITLE
Added setSecurementEncryptionOptionalParts into Wss4jSecurityInterceptor

### PR DESCRIPTION
**Pull request by xscreach**
Added ability to optionally encrypt XML elements - only when present in the XML

### CODE REVIEW

**Comment by xscreach** [comment]
Fixes #1101

**Comment by xscreach** [comment]
@gregturn sorry for bothering, just want to ask for PR review.
And... i haven't noticed the #1101 before i opened the PR, but if you guys would like to change the interceptor a bit differently (e.g. expose the handler field as protected to extending classes), please let me know, i'll update the PR 😉 

thanks in advance 🙇‍♂️

**Comment by free2create** [comment]
I don't know what the secret is to getting a PR merged but do [read over](https://github.com/spring-projects/spring-ws/blob/9a3da69a330bf99d52fe967f5bdf91fb754eccc8/CONTRIBUTING.adoc) their contributing guidelines :

**Comment by gregturn** [comment]
@xscreach Are you able to fashion a test case using this new feature?

**Comment by corneil** [comment]
Targeting unsupported branch

**Pull request closed without merging**
