### PR TITLE
Upgrade Axiom and use new API to convert Document to SOAPMessage

### PR DESCRIPTION
**Pull request by veithen**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@veithen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ws&pullRequestId=82)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-ws&pullRequestId=82) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@veithen Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ws&pullRequestId=82)!

**Comment by gregturn** [comment]
Thanks @veithen! We'll take it from here.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-ws/commit/f189e86c49e25464047859fe0247290a510ec7dc. Thanks @veithen!

**Pull request closed without merging**
