### PR TITLE
Exception handled by MessageDispatcher was logged with debug level

### PR DESCRIPTION
**Pull request by arkadius**
This exception can be a serious application error which will be omitted because of to low logging level. I suggest to change level to error or at least warning.

### CODE REVIEW

**Comment by poutsma** [comment]
Note that debug level is consistent with Spring's DispatcherServlet, see https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/DispatcherServlet.java#L1197

**Comment by arkadius** [comment]
True that, but Spring's DispatcherServlet rethrows exception which is eventually handled by servlet container which is reported e.g. in Jetty by o.e.jetty.servlet.ServletHandler with WARN level.
Spring-ws translates exceptions into soap faults so servlet container can't recognize that it is exceptional situation.
So IMO spring-ws is the only place where we can notify user that something is wrong.

**Comment by gregturn** [comment]
Why can't a user process a SOAP fault?

**Comment by gregturn** [comment]
Not seeing a valid reason for the user to handle a SOAP fault, I'm closing this PR as **works as designed**.

**Pull request closed without merging**
