### PR TITLE
WSS4J 2.x support

### PR DESCRIPTION
**Pull request by jaminh**
Issue: SWS-886

### CODE REVIEW

**Comment by poutsma** [comment]
Thank you, @jaminh, for creating this pull request and doing the hard work here! All the tests seem to run fine, so it looks like this Like I said in the [JIRA](https://jira.spring.io/browse/SWS-886), I do have some comments:

- I like the packaging structure you've used: `wss4j2` makes sense, especially in comparison with Spring Framework, where support for each Hibernate version lives in its own package (`hibernate4`, `hibernate5`)
- I like the similarity between our existing WSS4J 1.x support and this new 2.x support. Upgrading will mostly be as simple as changing the package name.
- I see that our full WS-Security tests suite works fine on WSS4J 2.x. Are there any issues that you are aware of?
- The Javadoc tags needs more work, though. Specifically: you should add your name as `@author` to all the classes in `wss4j2`, after the current authors. And the `@since` tags of those classes needs to say 2.3.
- The `package.html` in `wss4j2` needs to different than the one in `wss4j`: it needs to be clear that the former deals with WSS4J 2.
- The current WSS4J 1.x support needs to be deprecated, in favor of 2.x., though that's not necessarily something that needs to be in this PR.

As I said in the JIRA, these are issues that we can resolve as well. Just let me know what you think.

**Comment by jaminh** [comment]
I updated the Javadoc to include myself as an author and updated the package.html files. The only difference that is likely to have an effect on people updating is the UsernameTokenSignature action is no longer available. They discuss the reason behind removing that option here https://ws.apache.org/wss4j/migration/wss4j20.html. I did not deprecate the old Wss4j functionality.

**Comment by poutsma** [comment]
Looks good. This can be merged IMO.

**Comment by jaminh** [comment]
Do you want me to make another branch and squash the commits or is it fine as is?

**Comment by poutsma** [comment]
Yes, squashing commits would be preferable. Thanks!

**Comment by gregturn** [comment]
I'll review the final results and merge when I get online this morning.

**Comment by jaminh** [comment]
I made a new pull request with the commits squashed https://github.com/spring-projects/spring-ws/pull/54

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-ws/commit/f6f11b09d19297e446b1e01ad096aa244bdb5dfc.

Thanks @jaminh and @poutsma!

**Pull request closed without merging**
