### PR TITLE
Upgrade to Smack 4.1.6 and fix Smack dependencies

### PR DESCRIPTION
**Pull request by Flowdalic**

### CODE REVIEW

**Comment by Flowdalic** [comment]
Yes, a while ago.

**Comment by gregturn** [comment]
Wait a second. Does the mean smack now requires Java 7?  Right now we specific Java 6 as the minimum.

**Comment by Flowdalic** [comment]
Smack targets Java 7 since 4.0 (i.e. since more then 1 and a half year). But strictly speaking: It does not require Java 7. Although using a Java 6 JVM and Runtime may cause undesired behavior.

**Comment by gregturn** [comment]
@poutsma We've already pulled in Smack 4.1.5 to 2.3. Is Java 7 a reasonable criteria?

**Comment by poutsma** [comment]
Given that JDK 7 is pretty much EOL-ed, never mind JDK 6, I would say that bumping the JDK requirement to 7 would not be too adventurous ;).

**Comment by gregturn** [comment]
@Flowdalic Can you update your PR doing this:

1. Change it to SWS-941. I've already merged SWS-885 to master. This will keep the commit history clean.
2. Update build.gradle so that sourceCompatibility and targetCompatibility are set to 1.7.

Thanks!

**Comment by gregturn** [comment]
Nevermind, I got it done.

Resolved via https://github.com/spring-projects/spring-ws/commit/2787cbd677eb94e1dbd7246cb7d22af693f51c0d and https://github.com/spring-projects/spring-ws/commit/e6d9ae315dce881449396caea83ae865b2a39963

**Pull request closed without merging**
