### PR TITLE
SWS-981

### PR DESCRIPTION
**Pull request by jaminh**
SOAPAction header with SOAP ver 1.2 messages

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jaminh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ws&pullRequestId=81)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-ws&pullRequestId=81) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jaminh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ws&pullRequestId=81)!

**Comment by gregturn** [comment]
WIth no test cases to verify the proper behavior, I cannot proceed with this PR.

**Comment by jaminh** [comment]
I rebased and added tests, new pull request is https://github.com/spring-projects/spring-ws/pull/102.

**Pull request closed without merging**
