### PR TITLE
Update Smack to 4.0.0

### PR DESCRIPTION
**Pull request by Flowdalic**
spring-ws needs to be upgraded to use Smack 4.0 before spring-integration needs to be upgraded in [#1137](https://github.com/spring-projects/spring-integration/pull/1137)

### CODE REVIEW

**Comment by artembilan** [comment]
This one should be closed in favor of #48 .
Thank you @Flowdalic for the contribution anyway!

**Comment by gregturn** [comment]
I actually used this PR to write the other one. Salvaging the other was too difficult with all the master changes. Thanks!

**Comment by gregturn** [comment]
I plan to denote the commit here when completed.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-ws/commit/85c4832a7f30c1f5af98592eb8adfdf2ae22dfd0

**Pull request closed without merging**
